# Generated by Django 5.0.6 on 2024-06-05 09:42

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bestelling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klant_naam', models.CharField(default='Onbekend', max_length=100)),
                ('klant_bedrijf', models.CharField(blank=True, default='Geen bedrijf', max_length=100)),
                ('email', models.EmailField(default='onbekend@example.com', max_length=100)),
                ('telefoon', models.CharField(default='Onbekend', max_length=18)),
                ('facturatieadres', models.CharField(default='Onbekend adres', max_length=250)),
                ('afleveradres', models.CharField(default='Onbekend adres', max_length=250)),
                ('besteldatum', models.DateField(default=datetime.datetime.today)),
                ('voorschot', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('totaal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('betaling', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('ordered', 'Product besteld bij de fabrikant'), ('arrived', 'Product aangekomen in het magazijn'), ('ready_for_delivery', 'Product aangemeld voor levering'), ('shipped', 'Product verstuurd')], default='ordered', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Productnaam', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Klant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Voornaam', models.CharField(max_length=50)),
                ('Achternaam', models.CharField(max_length=50)),
                ('Bedrijf', models.CharField(max_length=50)),
                ('Facturatieadres', models.CharField(max_length=250)),
                ('Adres', models.CharField(max_length=250)),
                ('Telefoonnummer', models.CharField(max_length=18)),
                ('Email', models.EmailField(max_length=100)),
                ('Wachtwoord', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=100)),
                ('ean', models.CharField(max_length=50)),
                ('omschrijving', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('prijs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('image', models.ImageField(upload_to='uploads/product/')),
                ('korting', models.BooleanField(default=False)),
                ('korting_prijs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminInterface.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='BestellingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('omschrijving', models.CharField(blank=True, max_length=250, null=True)),
                ('hoeveelheid', models.IntegerField(default=1)),
                ('eenheidsprijs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('belastingen', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bestelling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminInterface.bestelling')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminInterface.product')),
            ],
        ),
        migrations.AddField(
            model_name='bestelling',
            name='producten',
            field=models.ManyToManyField(blank=True, through='AdminInterface.BestellingProduct', to='AdminInterface.product'),
        ),
    ]
