# Generated by Django 5.0.6 on 2024-06-11 19:41

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Klant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voornaam', models.CharField(max_length=50)),
                ('achternaam', models.CharField(max_length=50)),
                ('bedrijf', models.CharField(blank=True, max_length=50, null=True)),
                ('facturatieadres', models.CharField(max_length=250)),
                ('adres', models.CharField(max_length=250)),
                ('telefoonnummer', models.CharField(max_length=18)),
                ('email', models.EmailField(max_length=100)),
                ('wachtwoord', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SimpleTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Bestelling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('besteldatum', models.DateField(default=datetime.datetime.today)),
                ('voorschot', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('totaal', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('betaling', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('ordered', 'Product besteld bij de fabrikant'), ('arrived', 'Product aangekomen in het magazijn'), ('ready_for_delivery', 'Product aangemeld voor levering'), ('shipped', 'Product verstuurd')], default='ordered', max_length=20)),
                ('adres', models.CharField(blank=True, default='', max_length=250)),
                ('klant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminInterface.klant')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=100)),
                ('ean', models.CharField(blank=True, max_length=50, null=True)),
                ('omschrijving', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('prijs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/product/')),
                ('korting', models.BooleanField(default=False)),
                ('korting_prijs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminInterface.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='BestellingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('omschrijving', models.CharField(blank=True, max_length=250, null=True)),
                ('hoeveelheid', models.IntegerField(default=1)),
                ('eenheidsprijs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('belastingen', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bestelling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminInterface.bestelling')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminInterface.product')),
            ],
        ),
        migrations.AddField(
            model_name='bestelling',
            name='producten',
            field=models.ManyToManyField(blank=True, through='AdminInterface.BestellingProduct', to='AdminInterface.product'),
        ),
    ]
