# Generated by Django 5.0.6 on 2024-06-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminInterface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestelling',
            name='adres',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='bestelling',
            name='afleveradres',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='bestelling',
            name='betaling',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='bestelling',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bestelling',
            name='facturatieadres',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='bestelling',
            name='klant_bedrijf',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bestelling',
            name='klant_naam',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bestelling',
            name='status',
            field=models.CharField(choices=[('ordered', 'Besteld'), ('shipped', 'Verzonden')], default='ordered', max_length=20),
        ),
        migrations.AlterField(
            model_name='bestelling',
            name='telefoon',
            field=models.CharField(blank=True, default='', max_length=18),
        ),
    ]
