# Generated by Django 5.0.6 on 2024-06-03 19:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminInterface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestelling',
            name='Besteldatum',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='bestelling',
            name='Betaling',
            field=models.CharField(default='Onbekend', max_length=50),
        ),
        migrations.AddField(
            model_name='bestelling',
            name='Gewijzigde_datum',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bestelling',
            name='Totaal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bestelling',
            name='Voorschot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
