# Generated by Django 5.0.6 on 2024-06-07 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminInterface', '0002_bestelling_adres_alter_bestelling_afleveradres_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bestelling',
            name='afleveradres',
        ),
        migrations.RemoveField(
            model_name='bestelling',
            name='email',
        ),
        migrations.RemoveField(
            model_name='bestelling',
            name='facturatieadres',
        ),
        migrations.RemoveField(
            model_name='bestelling',
            name='klant_bedrijf',
        ),
        migrations.RemoveField(
            model_name='bestelling',
            name='klant_naam',
        ),
        migrations.RemoveField(
            model_name='bestelling',
            name='telefoon',
        ),
        migrations.AddField(
            model_name='bestelling',
            name='klant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AdminInterface.klant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bestelling',
            name='status',
            field=models.CharField(choices=[('ordered', 'Product besteld bij de fabrikant'), ('arrived', 'Product aangekomen in het magazijn'), ('ready_for_delivery', 'Product aangemeld voor levering'), ('shipped', 'Product verstuurd')], default='ordered', max_length=20),
        ),
    ]
