# Generated by Django 5.0.6 on 2024-06-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminInterface', '0003_remove_bestelling_afleveradres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestelling',
            name='totaal',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
